name: Cloudfront Function Test

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  AWS_REGION: "us-east-1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_READ_ONLY }}
          role-session-name: gh-actions-winglang-website-proxy-function-test
          aws-region: ${{ env.AWS_REGION }}
      - name: Run Cloudfront Function Test
        run: |
          npm install
          npm run test
