name: Pull Request Diff

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: write # This is required for commenting on PRs

env:
  AWS_REGION: "us-east-1"
  TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
  TF_BACKEND_BUCKET_REGION: ${{ secrets.TF_BACKEND_BUCKET_REGION }}
  DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
  DNSIMPLE_ACCOUNT: ${{ secrets.DNSIMPLE_ACCOUNT }}

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_READ_ONLY }}
          role-session-name: gh-actions-winglang-website-proxy-diff
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Winglang App
        uses: winglang/wing-github-action/actions/pull-request-diff@main
        with:
          entry: 'main.w'
          target: 'tf-aws'
          github-token: ${{ secrets.GITHUB_TOKEN }}